# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56c476fd68d4b20a9a9666f7058e15720a9d1509fd16ec085876cf34c35968f4e02b925b63fc12a79c74fb47d32c5ac2518f4af71cced8bf303cce26b041c61c

test:
  secret_key_base: 7240760e08b1e190fcb98edc23df1a3b033aab317754757d514b607b632f785b420ab1f204f86331ed68e50ae03219d56bb8f890e32a632c6699bd95dca4e66d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
