# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9ee3b3d2146daafc680a3fb8ea6df43d2f60c9b1c3830fe75c9ff9050f1b3c572100492eb868bc952fc3df3b72e19bb93515feca8cb7a28b53b8c63738015ff

test:
  secret_key_base: 8af6524c4cf93527b75e850f457596f7873e6046f2a997c25a3cc5e5e87a58b476e1fbdc11d95ac235757ade1c2b129f0c3c292ef83533cc14810e1299383372

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
